config/routes.rb
Rails.application.routes.draw do
  resources :tabs
  get 'users/:username', to: 'users#show', as: 'user'

  resources :items
  resources :wants do
    member do
      post 'vote', to: 'votes#create'
      delete 'unvote', to: 'votes#destroy'
    end
  end

  resources :tweets
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
  	get "signin", to: "devise/sessions#new"
  	delete "signout", to: "devise/sessions#destroy"
  	get "signup", to: "devise/registrations#new"
  end
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact-us', to: 'pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter
	def authorized?(action, subject = nil)
		user && user.admin?
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :title, presence: true
end

app/models/tab.rb
class Tab < ApplicationRecord
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :content, presence: true, length: { maximum: 140,
  	too_long: "%{count} characters is all you get" }

  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # removed :recoverable until mailer is setup
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :wants
  has_many :items
  has_many :tabs

  validates :username, presence: true, uniqueness: true, length: { minimum: 6 }
  validates :name, presence: true

  acts_as_voter
end

app/models/want.rb
class Want < ApplicationRecord
  belongs_to :user

  validates :user, presence: true

  acts_as_votable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def access_denied(exception)
  	redirect_to root_path, alert: "ye shall not pass"
  end

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_item, only: [:edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = current_user.items.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.new(item_params)

      if @item.save
        redirect_to @item, notice: 'Item was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
      if @item.update(item_params)
        redirect_to @item, notice: 'Item was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
      redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = current_user.items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :url, :text)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tabs_controller.rb
class TabsController < ApplicationController
  before_action :set_tab, only: [:show, :edit, :update, :destroy]

  # GET /tabs
  def index
    @tabs = Tab.all
  end

  # GET /tabs/1
  def show
  end

  # GET /tabs/new
  def new
    @tab = current_user.tabs.new
  end

  # GET /tabs/1/edit
  def edit
  end

  # POST /tabs
  def create
    @tab = current_user.tabs.new(tab_params)
      if @tab.save
        redirect_to @tab, notice: 'Tab was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /tabs/1
  def update
      if @tab.update(tab_params)
        redirect_to @tab, notice: 'Tab was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /tabs/1
  def destroy
    @tab.destroy
      redirect_to tabs_url, notice: 'Tab was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tab
      @tab = current_user.tabs.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tab_params
      params.require(:tab).permit(:title, :content)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find_by(username: params[:username])
  	@tweets = @user.tweets
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	before_action :authenticate_user!

	def create
		want = Want.find(params[:id])
		want.liked_by current_user
		redirect_to wants_path, notice: "Good on you for voting"
	end

	def destroy
		want = Want.find(params[:id])
		want.unliked_by current_user
		redirect_to wants_path, notice: "Wow, way to unvote"
	end
end

app/controllers/wants_controller.rb
class WantsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_want, only: [:edit, :update, :destroy]

  # GET /wants
  def index
    @wants = Want.all
  end

  # GET /wants/1
  def show
    @want = Want.find(params[:id])
  end

  # GET /wants/new
  def new
    @want = current_user.wants.new
  end

  # GET /wants/1/edit
  def edit
    @tweet = current_user.wants.find(params[:id])
  end

  # POST /wants
  def create
    @want = current_user.wants.new(want_params)

      if @want.save
        redirect_to @want, notice: 'Want was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /wants/1
  def update
      if @want.update(want_params)
        redirect_to @want, notice: 'Want was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /wants/1
  def destroy
    @want.destroy
      redirect_to wants_url, notice: 'Want was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_want
      @want = current_user.wants.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def want_params
      params.require(:want).permit(:user_id, :title, :summary, :fulldeets)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tabs_helper.rb
module TabsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wants_helper.rb
module WantsHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="container">
	<h1>Editing Item</h1>

	<%= render 'form', item: @item %>

	<%= link_to 'Show', @item %> |
	<%= link_to 'Back', items_path %>
</div>

app/views/items/index.html.erb
<div class="container">
  <h1>Items</h1>

  <table>
    <thead>
      <tr>
        <th>User</th>
        <th>Title</th>
        <th>Url</th>
        <th>Text</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.user.username %></td>
          <td><%= item.title %></td>
          <td><%= item.url %></td>
          <td><%= item.text %></td>
          <td><%= link_to 'Show', item %></td>
          <% if item.user == current_user %>
          <td><%= link_to 'Edit', edit_item_path(item) %></td>
          <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Item', new_item_path %>
</div>

app/views/items/new.html.erb
<div class="container">
	<h1>New Item</h1>

	<%= render 'form', item: @item %>

	<%= link_to 'Back', items_path %>
</div>

app/views/items/show.html.erb
<div class="container">
	<p>
	  <strong>User:</strong>
	  <%= @item.user.username %>
	</p>

	<p>
	  <strong>Title:</strong>
	  <%= @item.title %>
	</p>

	<p>
	  <strong>Url:</strong>
	  <%= @item.url %>
	</p>

	<% if @item.text? %>
		<p>
		  <strong>Text:</strong>
		  <%= @item.text %>
		</p>
	<% end %>

	<% if @item.user == current_user %>
	<%= link_to 'Edit', edit_item_path(@item) %> |
	<%= link_to 'Delete', @item, method: :delete %> |
	<% end %>
	<%= link_to 'Back', items_path %>
</div>

app/views/tabs/_form.html.erb
<%= form_for(tab) do |f| %>
  <% if tab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tab.errors.count, "error") %> prohibited this tab from being saved:</h2>

      <ul>
      <% tab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#thisone" role="tab"><%= f.text_field :title %></a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div class="tab-pane active" id="thisone" role="tabpanel"><%= f.text_area :content %></div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tabs/edit.html.erb
<div class="container">
	<h1>Editing Tab</h1>

	<%= render 'form', tab: @tab %>

	<%= link_to 'Show', @tab %> |
	<%= link_to 'Back', tabs_path %>
</div>

app/views/tabs/index.html.erb
<div class="container">
  <h1>Tabs</h1>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <% @tabs.each_with_index do |tab, i| %>
    <li class="nav-item">
      <a class="nav-link <% if i == 0 %>active<% end %>" data-toggle="tab" href="#<%= tab.title.parameterize %>" role="tab"><%= tab.title %></a>
    </li>
    <% end %>
    <li class="nav-item">
    <%= link_to '<i class="fa fa-plus-square-o" aria-hidden="true"></i>'.html_safe, new_tab_path, class: 'nav-link' %>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <% @tabs.each_with_index do |tab, i| %>
    <div class="tab-pane <% if i == 0 %>active<% end %>" id="<%= tab.title.parameterize %>" role="tabpanel"><%= tab.content %></div>
    <% end %>
  </div>

  <br>

</div>

app/views/tabs/new.html.erb
<div class="container">
	<h1>New Tab</h1>

	<%= render 'form', tab: @tab %>

	<%= link_to 'Back', tabs_path %>
</div>

app/views/tabs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @tab.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @tab.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tab.content %>
</p>

<%= link_to 'Edit', edit_tab_path(@tab) %> |
<%= link_to 'Back', tabs_path %>

app/views/tweets/_form.html.erb
<%= form_for(tweet, html: { multipart: true }) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<div class="container">
	<h1>Editing Tweet</h1>

	<%= render 'form', tweet: @tweet %>

	<%= link_to 'Show', @tweet %> |
	<%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class="container">
  <h1>Tweets</h1>

  <% if user_signed_in? %>
  <%= link_to 'New Tweet', new_tweet_path %>
  <% end %>
  <div class="list-group">
    <% @tweets.each do |tweet| %>
      <%= link_to tweet, class: "list-group-item list-group-item-action" do %>
        <h5 class="list-group-item-heading"><%= tweet.user.username %></h5>
        <% if tweet.image? %>
            <center><%= image_tag tweet.image %></center>
          <% end %>
        <p class="list-group-item-text"><%= tweet.content %></p>
      <% end %>
    <% end %>
  </div>

  <br>

</div>

app/views/tweets/new.html.erb
<div class="container">
	<h1>New Tweet</h1>

	<%= render 'form', tweet: @tweet %>

	<%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/show.html.erb
<div class="container">
	<div class="row">
		<div class="offset-md-2 col-md-8">
			<div class="card">
			  <% if @tweet.image? %>
			  	<center><%= image_tag @tweet.image, class: 'card-img-top' %></center>
			  <% end %>
			  <div class="card-block">
			    <h4 class="card-title"><%= link_to @tweet.user.username, user_path(@tweet.user.username) %></h4>
			    <p class="card-text"><%= @tweet.content %></p>
			    <div class="card-block">
				    <% if @tweet.user == current_user %>
			          <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_tweet_path(@tweet) %>
			          <%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, @tweet, method: :delete, data: { confirm: 'Don\'t want it anymore?' } %>
			        <% end %>
				    <%= link_to 'Back', tweets_path, class: "card-link" %>
				</div>
			  </div>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<h1><%= @user.username %></h1>
	<p><%= @user.name %></p>

	<table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>User</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tweets.each do |tweet| %>
        <tr>
          <td><%= tweet.user.username %></td>
          <td><%= tweet.content %></td>
          <td><%= link_to 'Show', tweet %></td>
          <% if tweet.user == current_user %>
            <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
            <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/wants/_form.html.erb
<%= form_for(want) do |f| %>
  <% if want.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(want.errors.count, "error") %> prohibited this want from being saved:</h2>

      <ul>
      <% want.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :fulldeets %>
    <%= f.text_area :fulldeets, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/wants/edit.html.erb
<div class="container">
	<h1>Editing Want</h1>

	<%= render 'form', want: @want %>

	<%= link_to 'Show', @want %> |
	<%= link_to 'Back', wants_path %>
</div>

app/views/wants/index.html.erb
<div class="container">
  <div class="title-area">
    <h1 class="page-title">Wants</h1> 
    <% if user_signed_in? %>
    <%= link_to 'New Want', new_want_path, class: 'btn btn-primary float-xs-right new' %>
    <% end %>
  </div>

  <div class="row">
      <% @wants.each do |want| %>
        <div class="col-sm-6">
          <%= link_to want do %>
          <div class="card card-block">
            
            <h4 class="card-title"><%= want.title %></h4>
            <p class="card-text"><%= want.summary %></p>
            <span class="vote_count">
              <%= want.votes_for.up.size %><br><small>Votes</small>
            </span>
            <% if user_signed_in? %>
              <% if current_user.voted_up_on? want %>
                <%= link_to '<i class="fa fa-arrow-circle-down" aria-hidden="true"></i>'.html_safe, unvote_want_path(want), method: :delete, class: "downvote" %>
              <% else %>
                <%= link_to '<i class="fa fa-arrow-circle-up" aria-hidden="true"></i>'.html_safe, vote_want_path(want), method: :post, class: "upvote" %>
              <% end %>
            <% end %>
            <td><%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_want_path(want), class: 'float-xs-left' %></td>
            <td><%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, want, method: :delete, data: { confirm: 'Don\'t want it anymore?' }, class: 'float-xs-left' %></td>
            <%= link_to 'More info', want, class: 'card-link btn btn-info float-xs-right' %>
            
          </div>
          <% end %>
        </div>
      <% end %>
  </div>

  <br>

</div>

app/views/wants/new.html.erb
<div class="container">
	<h1>New Want</h1>

	<%= render 'form', want: @want %>

	<%= link_to 'Back', wants_path %>
</div>

app/views/wants/show.html.erb
<div class="container">
	<p>
	  <strong>User:</strong>
	  <%= @want.user.username %>
	</p>

	<p>
	  <strong>Title:</strong>
	  <%= @want.title %>
	</p>

	<p>
	  <strong>Summary:</strong>
	  <%= @want.summary %>
	</p>

	<% if @want.fulldeets? %>
		<p>
		  <strong>Additional Details:</strong>
		  <%= @want.fulldeets %>
		</p>
	<% end %>

	<% if @want.user == current_user %>
	<%= link_to 'Edit', edit_want_path(@want) %> |
	<%= link_to 'Delete', @want, method: :delete %> |
	<% end %>
	<%= link_to 'Back', wants_path %>
</div>