config/routes.rb
Rails.application.routes.draw do
  resources :tabs
  get 'users/:username', to: 'users#show', as: 'user'

  resources :items
  resources :wants do
    member do
      post 'vote', to: 'votes#create'
      delete 'unvote', to: 'votes#destroy'
    end
  end

  resources :tweets
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
  	get "signin", to: "devise/sessions#new"
  	delete "signout", to: "devise/sessions#destroy"
  	get "signup", to: "devise/registrations#new"
  end
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact-us', to: 'pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter
	def authorized?(action, subject = nil)
		user && user.admin?
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :title, presence: true
end

app/models/tab.rb
class Tab < ApplicationRecord
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :content, presence: true, length: { maximum: 140,
  	too_long: "%{count} characters is all you get" }

  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # removed :recoverable until mailer is setup
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :wants
  has_many :items
  has_many :tabs

  validates :username, presence: true, uniqueness: true, length: { minimum: 6 }
  validates :name, presence: true

  acts_as_voter
end

app/models/want.rb
class Want < ApplicationRecord
  belongs_to :user

  validates :user, presence: true

  acts_as_votable
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_item, only: [:edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = current_user.items.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.new(item_params)

      if @item.save
        redirect_to @item, notice: 'Item was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
      if @item.update(item_params)
        redirect_to @item, notice: 'Item was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
      redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = current_user.items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :url, :text)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tabs_controller.rb
class TabsController < ApplicationController
  before_action :set_tab, only: [:show, :edit, :update, :destroy]

  # GET /tabs
  def index
    @tabs = Tab.all
  end

  # GET /tabs/1
  def show
  end

  # GET /tabs/new
  def new
    @tab = current_user.tabs.new
  end

  # GET /tabs/1/edit
  def edit
  end

  # POST /tabs
  def create
    @tab = current_user.tabs.new(tab_params)
      if @tab.save
        redirect_to @tab, notice: 'Tab was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /tabs/1
  def update
      if @tab.update(tab_params)
        redirect_to @tab, notice: 'Tab was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /tabs/1
  def destroy
    @tab.destroy
      redirect_to tabs_url, notice: 'Tab was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tab
      @tab = current_user.tabs.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tab_params
      params.require(:tab).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find_by(username: params[:username])
  	@tweets = @user.tweets
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	before_action :authenticate_user!

	def create
		want = Want.find(params[:id])
		want.liked_by current_user
		redirect_to wants_path, notice: "Good on you for voting"
	end

	def destroy
		want = Want.find(params[:id])
		want.unliked_by current_user
		redirect_to wants_path, notice: "Wow, way to unvote"
	end
end

app/controllers/wants_controller.rb
class WantsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_want, only: [:edit, :update, :destroy]

  # GET /wants
  def index
    @wants = Want.all
  end

  # GET /wants/1
  def show
    @want = Want.find(params[:id])
  end

  # GET /wants/new
  def new
    @want = current_user.wants.new
  end

  # GET /wants/1/edit
  def edit
    @tweet = current_user.wants.find(params[:id])
  end

  # POST /wants
  def create
    @want = current_user.wants.new(want_params)

      if @want.save
        redirect_to @want, notice: 'Want was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /wants/1
  def update
      if @want.update(want_params)
        redirect_to @want, notice: 'Want was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /wants/1
  def destroy
    @want.destroy
      redirect_to wants_url, notice: 'Want was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_want
      @want = current_user.wants.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def want_params
      params.require(:want).permit(:user_id, :title, :summary, :fulldeets)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tabs_helper.rb
module TabsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wants_helper.rb
module WantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Month Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-default navbar-dark bg-inverse text-xs-center text-md-left">
      <div class="container">
        <%= link_to "One Month Rails", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler hidden-lg-up float-xs-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"></button>
        <div class="collapse navbar-toggleable-md" id="navbarResponsive">
          <ul class="nav navbar-nav">
            <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Wants", wants_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Contact", contact_us_path, class: "nav-link" %></li>
            <% if user_signed_in? %>
            <li class="nav-item float-xs-right"><%= link_to "Logout", signout_path, method: :delete, class: "nav-link" %></li>
            <% else %>
            <li class="nav-item float-xs-right btn btn-primary"><%= link_to "Sign Up", signup_path %></li>
            <li class="nav-item float-xs-right"><%= link_to "Sign In", signin_path, class: "nav-link" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Alerts -->
    <% flash.each do |name, message| %>
    <%= content_tag(:div, message, class: "alert alert-info text-xs-center #{name}") %>
    <% end %>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 One Month</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>
</div>
<div class="container">
	<div class="row">
		<h2>More here as I figure out what I'm doing</h2>
		<p>Cat ipsum dolor sit amet, british shorthair. Leopard thai. British shorthair american shorthair or leopard but siamese havana brown. Cheetah egyptian mau so cornish rex. Singapura. Lion cheetah and american bobtail so himalayan so russian blue or kitty thai. Grimalkin norwegian forest himalayan. Russian blue savannah kitten so persian. Devonshire rex grimalkin or donskoy, but bobcat tiger cheetah grimalkin. Birman grimalkin himalayan grimalkin for tabby or manx. Abyssinian himalayan or tiger. British shorthair persian cougar thai american bobtail so bengal. Havana brown scottish fold. Norwegian forest. Kitty egyptian mau and savannah. Himalayan. Ocicat. Singapura himalayan birman grimalkin munchkin munchkin american shorthair. Scottish fold bombay so himalayan but singapura egyptian mau so sphynx. American bobtail. Tabby balinese . Devonshire rex birman yet maine coon turkish angora or persian manx havana brown. Scottish fold birman, scottish fold bengal yet mouser bobcat for mouser. Sphynx turkish angora or donskoy or grimalkin manx and sphynx and thai. Lion havana brown lion scottish fold.</p>

		<p>American bobtail kitty, singapura. Russian blue bombay. Tomcat. Kitty scottish fold but american shorthair. American bobtail grimalkin kitty thai. Burmese balinese . Tabby. Tiger jaguar or sphynx, but sphynx burmese. Cheetah himalayan siberian. Savannah cheetah but singapura ocicat cougar american bobtail birman. Birman cornish rex. Himalayan bobcat maine coon manx. Munchkin. Tomcat ocelot. Cougar. Bengal. Mouser burmese siberian for malkin so cheetah egyptian mau. Leopard donskoy american bobtail birman ragdoll ragdoll and cheetah. Tom cornish rex russian blue thai. Thai. Siamese bengal or tomcat.</p>

		<p>Jaguar balinese , or abyssinian kitten malkin burmese. Ragdoll donskoy yet sphynx maine coon havana brown so tiger. Lynx. Tiger birman munchkin yet american shorthair tomcat and devonshire rex sphynx. Singapura burmese, manx or kitten yet panther norwegian forest tomcat. Malkin tomcat american shorthair but cheetah so tiger or balinese , burmese. Cheetah british shorthair and british shorthair, and siberian munchkin leopard manx. Sphynx leopard so sphynx. Malkin bombay, but siberian for devonshire rex, ocicat norwegian forest. Scottish fold thai. Malkin. Munchkin birman american shorthair or malkin yet sphynx scottish fold norwegian forest. Lion. Norwegian forest leopard ocicat and donskoy but malkin but grimalkin for panther.</p>
	</div>
</div>

app/views/pages/contact.html.erb
<div class="jumbotron">
    <div class="container center-block">
        <h1>Contact</h1>
		<p>Mail by pigeon only.</p>
		<img src="https://s-media-cache-ak0.pinimg.com/236x/20/d7/f6/20d7f6b81a529b69120663f240f7d6c9.jpg">
		<br>
		<sub>If the pigeon is unavailable, try another bird: <%= link_to '@SomewhatRounded', 'https://twitter.com/somewhatrounded' %></sub>
		<br>
        <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>
</div>
<div class="container">
	<div class="row">
		<h2>There probably won't be much more here</h2>
		<p>Cat ipsum dolor sit amet, devonshire rex siberian. Maine coon birman, yet tiger or cornish rex tiger and munchkin and cougar. Ocicat. Jaguar scottish fold and himalayan lynx lynx for devonshire rex. Tom grimalkin bobcat or savannah. Sphynx. American shorthair turkish angora cornish rex lynx cougar. Lynx lynx ocelot yet burmese. Bengal cougar, british shorthair ocelot so mouser for tomcat. Kitty bobcat. Munchkin siberian for siamese but puma. British shorthair havana brown. Egyptian mau abyssinian . Manx ragdoll mouser cheetah cheetah. Panther maine coon yet donskoy and jaguar. Panther kitten but scottish fold yet manx cougar ocicat. Tomcat. Norwegian forest puma cheetah but grimalkin. Cornish rex thai bengal yet siamese. Kitten. Kitty birman cheetah bobcat cheetah. Kitten siberian but kitten and maine coon for siamese, for bobcat cougar. </p>
	</div>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
    <div class="jumbotron jumbotron-home text-xs-center">
        <div class="container">
            <h1>Welcome back!</h1>
        </div>
    </div>
<% else %>
    <div class="jumbotron jumbotron-home text-xs-center">
        <div class="container">
            <h1>Welcome to my website!</h1>
            <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
            <%= link_to "Learn more »", about_path, class: "btn btn-primary btn-lg" %> 
        </div>
    </div>
    <div class="container">
        <div class="row text-xs-center">
            <div class="col-md-4">
                <h2>Thing One</h2>
                <img src="http://placehold.it/200x200" alt="Just a thing" class="rounded-circle">
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
            </div>
            <div class="col-md-4">
                <h2>Thing Two</h2>
                <img src="http://placehold.it/200x200" alt="Just a thing" class="rounded-circle">
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
            </div>
            <div class="col-md-4">
                <h2>Thing Three</h2>
                <img src="http://placehold.it/200x200" alt="Just a thing" class="rounded-circle">
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row marketing">
            <div class="col-lg-6">
              <h4>Subheading</h4>
              <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

              <h4>Subheading</h4>
              <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

              <h4>Subheading</h4>
              <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
            </div>

            <div class="col-lg-6">
              <h4>Subheading</h4>
              <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

              <h4>Subheading</h4>
              <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

              <h4>Subheading</h4>
              <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
            </div>
        </div>
    </div>
    <div class="callout">
        <div class="container">
            <div class="row text-xs-center">
                <h3>Check it out and get started!</h3>
                <p>
                <%= link_to "Sign Up", signup_path, class: "btn btn-secondary" %>
                <%= link_to "Sign In", signin_path, class: "btn btn-secondary" %>
                </p>
            </div>
        </div>
    </div>
<% end %>